service: torivahti-agent

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-north-1
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

functions:
  post:
    handler: handler.hello
    events:
      - http:
          path: torivahti-agent
          method: post
          cors: true